# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=26.1
loader_version=0.18.4
# Mod Properties
version=3.2.0+26.1.x
maven_group=me.coolaid
archives_base_name=enhancedkeybinds
# Dependencies
fabric_version=0.150.0+26.1.2
modmenu_version=18.0.0-beta.1
yacl_version=3.9.4+26.1-fabric
amecs_version=amecs-key-modifiers-mc26.1.0:1.0.2