# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=26.1
loader_version=0.18.0
# Mod Properties
version=3.0.0
maven_group=coolaid
archives_base_name=enhancedkeybinds
# Dependencies
fabric_version=0.144.0+26.1
modmenu_version=18.0.0-alpha.6
yacl_version=3.9.0+26.1-fabric
amecs_version=amecs-key-modifiers-mc26.1.0:1.0.2
